# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#

# config/database.yml

development:
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: db/development.sqlite3

test:
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: db/test.sqlite3

production:
  primary:
    adapter: postgresql
    url: <%= ENV['DATABASE_URL'] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  cache:
    adapter: postgresql
    url: <%= ENV['DATABASE_URL'] %>

  queue:
    adapter: postgresql
    url: <%= ENV['DATABASE_URL'] %>

  cable:
    adapter: postgresql
    url: <%= ENV['DATABASE_URL'] %>